services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backbone
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack: 
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sns,sqs
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - ./.docker/localstack/bootstrap.sh:/etc/localstack/init/ready.d/01-bootstrap.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backbone
    healthcheck:
      test: ["CMD", "awslocal", "sqs", "list-queues"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - localstack
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backbone

volumes:
  postgres:

networks:
  backbone:
    driver: bridge