// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "List all categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.CategoryResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "CreateCategory a new category",
                "parameters": [
                    {
                        "description": "Category to create",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.CreateCategorySchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/schemas.CategoryResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCategoryDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get a Category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.CategoryResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCategoryDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.CategoryNotFoundErrorSchema"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "UpdateCategory a Category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Category data",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateCategoryRequestBodySchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.CategoryResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCategoryDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.CategoryNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "DeleteCategory a Category by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Category Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCategoryDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/customers/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "List all customers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.CustomerResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_customer_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Create a new customer",
                "parameters": [
                    {
                        "description": "Customer to create",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.CreateCustomerRequestBodySchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCustomerDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_customer_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/customers/cpf/{cpf}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Get a customer by CPF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer Cpf",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCustomerDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerNotFoundErrorSchema"
                        }
                    }
                }
            }
        },
        "/customers/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Get a customer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCustomerDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerNotFoundErrorSchema"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Update a customer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated customer data",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateCustomerRequestBodySchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCustomerDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.CustomerNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_customer_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Delete a customer by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Customer ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidCustomerDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_customer_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/kitchen-orders/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KitchenOrders"
                ],
                "summary": "List all kitchenOrders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.KitchenOrderResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_kitchen-order_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/kitchen-orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KitchenOrders"
                ],
                "summary": "Get a kitchenOrder by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KitchenOrder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidKitchenOrderDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderNotFoundErrorSchema"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KitchenOrders"
                ],
                "summary": "Update a kitchenOrder by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KitchenOrder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated kitchenOrder data",
                        "name": "kitchenOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateKitchenOrderSchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidKitchenOrderDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.KitchenOrderNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_kitchen-order_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/order/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Delete a order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidOrderDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_order_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/orders/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "List all orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.OrderResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_order_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Create a new order",
                "parameters": [
                    {
                        "description": "Order to create",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.CreateOrderRequestBodySchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/schemas.OrderWithPaymentResponseSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_order_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get a order by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.OrderResponseSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.OrderNotFoundException"
                        }
                    }
                }
            }
        },
        "/payments/webhook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Confirm Payment",
                "responses": {}
            }
        },
        "/payments/{orderID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Get a payment by OrderID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "orderID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/products/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "List all products",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by category ID",
                        "name": "category_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schemas.ProductResponseSchema"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product to create",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.CreateProductSchema"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductNotFoundErrorSchema"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Update a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated product data",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schemas.UpdateProductRequestBodySchema"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductResponseSchema"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete a product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/products/{id}/images": {
            "patch": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Add image to a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        },
        "/products/{id}/images/{image_file_name}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete an image from a product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nome do arquivo da imagem",
                        "name": "image_file_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/schemas.InvalidProductDataErrorSchema"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/schemas.ProductNotFoundErrorSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemas.CategoryNotFoundErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Category not found"
                }
            }
        },
        "schemas.CategoryResponseSchema": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "Bebidas"
                }
            }
        },
        "schemas.CreateCategorySchema": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schemas.CreateCustomerRequestBodySchema": {
            "type": "object",
            "required": [
                "cpf",
                "email",
                "name"
            ],
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                }
            }
        },
        "schemas.CreateOrderItemsRequestBodySchema": {
            "type": "object",
            "required": [
                "product_id",
                "quantity"
            ],
            "properties": {
                "product_id": {
                    "type": "string",
                    "example": "123"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "schemas.CreateOrderRequestBodySchema": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 10.5
                },
                "customer_id": {
                    "type": "string",
                    "example": "123"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.CreateOrderItemsRequestBodySchema"
                    }
                }
            }
        },
        "schemas.CreateProductSchema": {
            "type": "object",
            "required": [
                "category_id",
                "description",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "schemas.CustomerNotFoundErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Customer not found"
                }
            }
        },
        "schemas.CustomerResponseSchema": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                }
            }
        },
        "schemas.ImageResponseSchema": {
            "type": "object",
            "properties": {
                "file_name": {
                    "type": "string",
                    "example": "image.jpg"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                }
            }
        },
        "schemas.InvalidCategoryDataErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid category data"
                }
            }
        },
        "schemas.InvalidCustomerDataErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid customer data"
                }
            }
        },
        "schemas.InvalidKitchenOrderDataErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid kitchen order data"
                }
            }
        },
        "schemas.InvalidOrderDataErrorSchema": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "schemas.InvalidProductDataErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid product data"
                }
            }
        },
        "schemas.KitchenOrderNotFoundErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Kitchen order not found"
                }
            }
        },
        "schemas.KitchenOrderResponseSchema": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                },
                "order_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "slug": {
                    "type": "string",
                    "example": "001"
                },
                "status": {
                    "type": "string",
                    "example": "Pronto"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                }
            }
        },
        "schemas.OrderItemResponseSchema": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "product_id": {
                    "type": "string",
                    "example": "123"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "unit_price": {
                    "type": "number",
                    "example": 19.99
                }
            }
        },
        "schemas.OrderNotFoundException": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "schemas.OrderResponseSchema": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 10.5
                },
                "customer_id": {
                    "type": "string",
                    "example": "123"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.OrderItemResponseSchema"
                    }
                }
            }
        },
        "schemas.OrderWithPaymentResponseSchema": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/schemas.OrderResponseSchema"
                },
                "payment": {
                    "$ref": "#/definitions/tech_challenge_internal_order_infra_api_schemas.PaymentResponseSchema"
                }
            }
        },
        "schemas.ProductNotFoundErrorSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Product not found"
                }
            }
        },
        "schemas.ProductResponseSchema": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "category_id": {
                    "type": "string",
                    "example": "2cb7f56d-89a1-4e60-b488-65dc4ffacbc6"
                },
                "description": {
                    "type": "string",
                    "example": "Lanche com carne, queijo, alface e tomate"
                },
                "id": {
                    "type": "string",
                    "example": "76fbddb3-3e2f-4f5f-a4e1-30a0a2384eae"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schemas.ImageResponseSchema"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "X-Salada"
                },
                "price": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "schemas.UpdateCategoryRequestBodySchema": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "schemas.UpdateCustomerRequestBodySchema": {
            "type": "object",
            "required": [
                "cpf",
                "email",
                "name"
            ],
            "properties": {
                "cpf": {
                    "type": "string",
                    "example": "12345678901"
                },
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "João Silva"
                }
            }
        },
        "schemas.UpdateKitchenOrderSchema": {
            "type": "object",
            "required": [
                "status_id"
            ],
            "properties": {
                "status_id": {
                    "type": "string"
                }
            }
        },
        "schemas.UpdateProductRequestBodySchema": {
            "type": "object",
            "required": [
                "category_id",
                "description",
                "name"
            ],
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "category_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "tech_challenge_internal_customer_infra_api_schemas.ErrorMessageSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "tech_challenge_internal_kitchen-order_infra_api_schemas.ErrorMessageSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "tech_challenge_internal_order_infra_api_schemas.ErrorMessageSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "tech_challenge_internal_order_infra_api_schemas.PaymentResponseSchema": {
            "type": "object",
            "properties": {
                "data": {},
                "payment_type": {
                    "type": "string",
                    "example": "PIX"
                }
            }
        },
        "tech_challenge_internal_product_infra_api_schemas.ErrorMessageSchema": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "Tech Challenge API",
	Description:      "This is an API for a tech challenge.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
