basePath: /v1
host: localhost:8080
info:
  contact: {}
  description: This is an API for a payments on tech challenge.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Microservice Payment
  version: "1.0"
paths:
  /payments/order/{orderID}:
    get:
      parameters:
      - description: Order ID
        in: path
        name: orderID
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get a payment by OrderID
      tags:
      - Payments
  /payments/pix:
    post:
      consumes:
      - application/json
      responses: {}
      summary: Create Pix Billing
      tags:
      - Payments
  /payments/webhook:
    post:
      consumes:
      - application/json
      responses: {}
      summary: Confirm Payment
      tags:
      - Payments
schemes:
- http
swagger: "2.0"
