name: Validation

on: 
  pull_request: 
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - './**'

  workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  
jobs:
  analyze:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    env:
      SONAR_PROJECT_KEY: "FIAP-11soat-grupo-21_api-microservice-payment"
      SONAR_ORGANIZATION: "fiap-11soat-grupo-21"
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
          
      - name: Install Dependencies
        working-directory: ./
        run: go mod tidy

      - name: Run Tests and Generate Coverage
        working-directory: ./
        run: |
          go test ./... -coverprofile=coverage.out
      
      - name: Run GolangCI-Lint
        working-directory: ./
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          golangci-lint run --out-format json > golangci-lint-report.json

      - name: Run Gosec Security Scanner
        working-directory: ./
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          gosec -no-fail -fmt=sonarqube -out report.json ./...
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.verbose=true
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.coverage.exclusions="**/*_test.go,**/*mock*.go,**/mocks/**"
  
  RunTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Execute unit tests
        working-directory: ./
        run: |
          go test ./... -v 
